javac -d c:\javawebserver2.0\servlets application.java
javac -d c:\javawebserver2.0\servlets subtypes.java
javac -d c:\javawebserver2.0\servlets subtypeid.java
javac -d c:\javawebserver2.0\servlets trials.java
javac -d c:\javawebserver2.0\servlets trialapp.java
javac -d c:\javawebserver2.0\servlets trials1.java
javac -d c:\javawebserver2.0\servlets projserv.java
javac -d c:\javawebserver2.0\servlets billapp.java
javac -d c:\javawebserver2.0\servlets GoBack.java
javac -d c:\javawebserver2.0\servlets projserv1.java
javac -d c:\javawebserver2.0\servlets sign_up.java
javac -d c:\javawebserver2.0\servlets submit.java
javac -d c:\javawebserver2.0\servlets submit1.java
javac -d c:\javawebserver2.0\servlets LoginCheck.java
javac -d c:\javawebserver2.0\servlets FeedSubmit.java



