import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;


public class  docreg  extends HttpServlet
{
Statement st;
Connection con;
String s;
	public void doGet(HttpServletRequest req,HttpServletResponse res)
	{
	try
	{
PrintWriter out = res.getWriter();
Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
con = DriverManager.getConnection("jdbc:odbc:reddy","chinnu","nisha");
st=con.createStatement();
ResultSet rs,rs1;
res.setContentType("text/html");
String uid=req.getParameter("username");
System.out.println(uid);
rs1=st.executeQuery("select * from dpersonal where username='"+uid+"'");
		 if(rs1.next())
		 {
		  out.println("<br><br><br><center><body background='c:/javawebserver2.0/servlets/wedflo_15.gif'>");
		 out.println("<table border=12 bordercolor=green bgcolor=orange>");
         out.println("<tr><td><br><br><h3>You are already registered:</h3>");
		 out.println("<br><br>");
		 out.println("<center><input type=button value=back onclick=window.history.go(-1)></center>");
		 	 out.println("</td></tr></table></center></body>");
		 		 }
		 else
		 {
rs=st.executeQuery("select doctorcode from dpersonal order by to_number(doctorcode)");
while(rs.next())
s = rs.getString("doctorcode");
System.out.println("after while : "+s);
int i=Integer.parseInt(s);
i=i+1;
s = Integer.toString(i);
System.out.println("next number : "+s);
out.println("<HTML>");
out.println("<HEAD>");
out.println("<TITLE>DOCTOR'S REGISTRATION </TITLE>");
out.println("<script language = javascript>");
out.println("function doccheck() ");
out.println("{");
out.println("var str2=document.doct.dname.value;");
out.println("var str3=document.doct.dage.value;");
out.println("var str4=document.doct.dqual.value;");
out.println("var str5=document.doct.dspec.value;");
out.println("var str6=document.doct.dexp.value;");
out.println("var str7=document.doct.dachieve.value;");
out.println("var str8=document.doct.dhno.value;");
out.println("var str9=document.doct.dstr.value;");
out.println("var str10=document.doct.dcity.value;");
out.println("var str11=document.doct.dstate.value;");
out.println("var str12=document.doct.dcountry.value;");
out.println("var str13=document.doct.dzcode.value;");
out.println("var str14=document.doct.dwphone.value;");
out.println("var str15=document.doct.drphone.value;");
out.println("var str16=document.doct.dmobile.value;");
out.println("var str17=document.doct.dfax.value;");
out.println("var str18=document.doct.demail.value;");
out.println("var str19=document.doct.datime.value;");
out.println("var str20=document.doct.dh1name.value;");
out.println("var str21=document.doct.dh1hno.value;");
out.println("var str22=document.doct.dh1str.value;");
out.println("var str23=document.doct.dh1city.value;");
out.println("var str24=document.doct.dh1state.value;");
out.println("var str25=document.doct.dh1country.value;");
out.println("var str26=document.doct.dh1w1phone.value;");
out.println("var str27=document.doct.dh1w2phone.value;");
out.println("var str28=document.doct.dh1fax.value;");
out.println("var str29=document.doct.dh1url.value;");
out.println("var str30=document.doct.dh2name.value;");
out.println("var str31=document.doct.dh2hno.value;");
out.println("var str32=document.doct.dh2str.value;");
out.println("var str33=document.doct.dh2city.value;");
out.println("var str34=document.doct.dh2state.value;");
out.println("var str35=document.doct.dh2country.value;");
out.println("var str36=document.doct.dh2dw1phone.value;");
out.println("var str37=document.doct.h2dw2phone.value;");
out.println("var str38=document.doct.dh2fax.value;");
out.println("var str39=document.doct.dh2url.value;");
out.println("var str40=document.doct.dh3name.value;");
out.println("var str41=document.doct.dh3hno.value;");
out.println("var str42=document.doct.dh3str.value;");
out.println("var str43=document.doct.dh3city.value;");
out.println("var str44=document.doct.dh3state.value;");
out.println("var str45=document.doct.dh3country.value;");
out.println("var str46=document.doct.dh3dw1phone.value;");
out.println("var str47=document.doct.dh3dw2phone.value;");
out.println("var str48=document.doct.dh3fax.value;");
out.println("var str49=document.doct.dh3url.value;");
out.println("var str50=document.doct.h1dwbname.value;");
out.println("var str51=document.doct.h1dwbcity.value;");
out.println("var str52=document.doct.h1dwbstate.value;");
out.println("var str53=document.doct.h1dwbcountry.value;");
out.println("var str54=document.doct.h1dwbphone.value;");
out.println("var str55=document.doct.h2dwbname.value;");
out.println("var str56=document.doct.h2dwbcity.value;");
out.println("var str57=document.doct.h2dwbstate.value;");
out.println("var str58=document.doct.h2dwbcountry.value;");
out.println("var str59=document.doct.h2dwbphone.value;");
out.println("var l2=document.doct.dname.value.length;");
out.println("var l3=document.doct.dage.value.length;");
out.println("var l4=document.doct.dqual.value.length;");
out.println("var l5=document.doct.dspec.value.length;");
out.println("var l7=document.doct.dachieve.value.length;");
out.println("var l8=document.doct.dhno.value.length;");
out.println("var l9=document.doct.dstr.value.length;");
out.println("var l10=document.doct.dcity.value.length;");
out.println("var l11=document.doct.dstate.value.length;");
out.println("var l12=document.doct.dcountry.value.length;");
out.println("var l13=document.doct.dzcode.value.length;");
out.println("var l14=document.doct.dwphone.value.length;");
out.println("var l15=document.doct.drphone.value.length;");
out.println("var l16=document.doct.dmobile.value.length;");
out.println("var l17=document.doct.dfax.value.length;");
out.println("var l18=document.doct.demail.value.length;");
out.println("var l19=document.doct.datime.value.length;");
out.println("var l20=document.doct.dh1name.value.length;");
out.println("var l21=document.doct.dh1hno.value.length;");
out.println("var l22=document.doct.dh1str.value.length;");
out.println("var l23=document.doct.dh1city.value.length;");
out.println("var l24=document.doct.dh1state.value.length;");
out.println("var l25=document.doct.dh1country.value.length;");
out.println("var l26=document.doct.dh1w1phone.value.length;");
out.println("var l27=document.doct.dh1w2phone.value.length;");
out.println("var l28=document.doct.dh1fax.value.length;");
out.println("var l29=document.doct.dh1url.value.length;");
out.println("var l30=document.doct.dh2name.value.length;");
out.println("var l31=document.doct.dh2hno.value.length;");
out.println("var l32=document.doct.dh2str.value.length;");
out.println("var l33=document.doct.dh2city.value.length;");
out.println("var l34=document.doct.dh2state.value.length;");
out.println("var l35=document.doct.dh2country.value.length;");
out.println("var l36=document.doct.dh2dw1phone.value.length;");
out.println("var l37=document.doct.h2dw2phone.value.length;");
out.println("var l38=document.doct.dh2fax.value.length;");
out.println("var l39=document.doct.dh2url.value.length;");
out.println("var l40=document.doct.dh3name.value.length;");
out.println("var l41=document.doct.dh3hno.value.length;");
out.println("var l42=document.doct.dh3str.value.length;");
out.println("var l43=document.doct.dh3city.value.length;");
out.println("var l44=document.doct.dh3state.value.length;");
out.println("var l45=document.doct.dh3country.value.length;");
out.println("var l46=document.doct.dh3dw1phone.value.length;");
out.println("var l47=document.doct.dh3dw2phone.value.length;");
out.println("var l48=document.doct.dh3fax.value.length;");
out.println("var l49=document.doct.dh3url.value.length;");
out.println("var l50=document.doct.h1dwbname.value.length;");
out.println("var l51=document.doct.h1dwbcity.value.length;");
out.println("var l52=document.doct.h1dwbstate.value.length;");
out.println("var l53=document.doct.h1dwbcountry.value.length;");
out.println("var l54=document.doct.h1dwbphone.value.length;");
out.println("var l55=document.doct.h2dwbname.value.length;");
out.println("var l56=document.doct.h2dwbcity.value.length;");
out.println("var l57=document.doct.h2dwbstate.value.length;");
out.println("var l58=document.doct.h2dwbcountry.value.length;");
out.println("var l59=document.doct.h2dwbphone.value.length;");

out.println("if(str2==\"\")");
out.println("{");
out.println("alert(\"Enter the Doctor Name field\");");
out.println("document.doct.dname.focus();");
out.println("document.doct.dname.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str3==\"\")");
out.println("{");
out.println("alert(\"Enter the Age field\");");
out.println("document.doct.dage.focus();");
out.println("document.doct.dage.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(isNaN(str3)){");
out.println("alert(\"Enter only numeric values in Age field\");");
out.println("document.doct.dage.focus();");
out.println("document.doct.dage.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str4==\"\")");
out.println("{");
out.println("alert(\"Enter the Doctor Qualification field\");");
out.println("document.doct.dqual.focus();");
out.println("document.doct.dqual.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str9==\"\")");
out.println("{");
out.println("alert(\"Enter the Street field\");");
out.println("document.doct.dstr.focus();");
out.println("document.doct.dstr.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str10==\"\")");
out.println("{");
out.println("alert(\"Enter the City field\");");
out.println("document.doct.dcity.focus();");
out.println("document.doct.dcity.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str11==\"\")");
out.println("{");
out.println("alert(\"Enter the  State field\");");
out.println("document.doct.dstate.focus();");
out.println("document.doct.dstate.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str12==\"\")");
out.println("{");
out.println("alert(\"Enter the Country field\");");
out.println("document.doct.dcountry.focus();");
out.println("document.doct.dcountry.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str18==\"\")");
out.println("{");
out.println("alert(\"Enter the Email Id field\");");
out.println("document.doct.demail.focus();");
out.println("document.doct.demail.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str19==\"\")");
out.println("{");
out.println("alert(\"Enter the Available Timings field\");");
out.println("document.doct.datime.focus();");
out.println("document.doct.datime.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str20==\"\")");
out.println("{");
out.println("alert(\"Enter the Hospital 1 Name field\");");
out.println("document.doct.dh1name.focus();");
out.println("document.doct.dh1name.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str22==\"\")");
out.println("{");
out.println("alert(\"Enter the hospital 1 Street  field\");");
out.println("document.doct.dh1str.focus();");
out.println("document.doct.dh1str.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str23==\"\")");
out.println("{");
out.println("alert(\"Enter the hosp1 city field\");");
out.println("document.doct.dh1city.focus();");
out.println("document.doct.dh1city.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str24==\"\")");
out.println("{");
out.println("alert(\"Enter the hosp1 state field\");");
out.println("document.doct.dh1state.focus();");
out.println("document.doct.dh1state.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(str25==\"\")");
out.println("{");
out.println("alert(\"Enter the hosp1 country field\");");
out.println("document.doct.dh1country.focus();");
out.println("document.doct.dh1country.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l2>25){");
out.println("alert(\"Doctor Name must not exceed 25 chars\");");
out.println("document.doct.dname.focus();");
out.println("document.doct.dname.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l3>3){");
out.println("alert(\"Age field must not exceed 3 chars\");");
out.println("document.doct.dage.focus();");
out.println("document.doct.dage.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l4>30){");
out.println("alert(\"Qualification must not exceed 30 chars\");");
out.println("document.doct.dqual.focus();");
out.println("document.doct.dqual.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l5>30){");
out.println("alert(\"Specialization field must not exceed 30 chars\");");
out.println("document.doct.dspec.focus();");
out.println("document.doct.dspec.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l7>70){");
out.println("alert(\"achievement field must not exceed 70 chars\");");
out.println("document.doct.dachieve.focus();");
out.println("document.doct.dachieve.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l8>15){");
out.println("alert(\"House no. must not exceed 15 chars\");");
out.println("document.doct.dhno.focus();");
out.println("document.doct.dhno.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l9>20){");
out.println("alert(\"Street field must not exceed 20 chars\");");
out.println("document.doct.dstr.focus();");
out.println("document.doct.dstr.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l10>20){");
out.println("alert(\"City field must not exceed 20 chars\");");
out.println("document.doct.dcity.focus();");
out.println("document.doct.dcity.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l11>20){");
out.println("alert(\"State field must not exceed 20 chars\");");
out.println("document.doct.dstate.focus();");
out.println("document.doct.dstate.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l12>20){");
out.println("alert(\"Country field must not exceed 20 chars\");");
out.println("document.doct.dcountry.focus();");
out.println("document.doct.dcountry.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l13>15){");
out.println("alert(\"Zip Code field must not exceed 15 chars\");");
out.println("document.doct.dzcode.focus();");
out.println("document.doct.dzcode.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l14>15){");
out.println("alert(\"Work Phone must not exceed 15 chars\");");
out.println("document.doct.dwphone.focus();");
out.println("document.doct.dwphone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l15>15){");
out.println("alert(\"Resi Phone must not exceed 15 chars\");");
out.println("document.doct.drphone.focus();");
out.println("document.doct.drphone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l16>20){");
out.println("alert(\"Mobile field must not exceed 20 chars\");");
out.println("document.doct.dmobile.focus();");
out.println("document.doct.dmobile.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l17>20){");
out.println("alert(\"Fax field must not exceed 20 chars\");");
out.println("document.doct.dfax.focus();");
out.println("document.doct.dfax.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l18>30){");
out.println("alert(\"Email Id must not exceed 30 chars\");");
out.println("document.doct.demail.focus();");
out.println("document.doct.demail.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l19>25){");
out.println("alert(\"Avail Time field must not exceed 25 chars\");");
out.println("document.doct.datime.focus();");
out.println("document.doct.datime.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l20>30){");
out.println("alert(\"hosp1 name must not exceed 30 chars\");");
out.println("document.doct.dh1name.focus();");
out.println("document.doct.dh1name.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l21>15){");
out.println("alert(\"hosp1 H.No. must not exceed 15 chars\");");
out.println("document.doct.dh1hno.focus();");
out.println("document.doct.dh1hno.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l22>20){");
out.println("alert(\"hosp1 Street must not exceed 20 chars\");");
out.println("document.doct.dh1str.focus();");
out.println("document.doct.dh1str.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l23>20){");
out.println("alert(\"hosp1 City must not exceed 20 chars\");");
out.println("document.doct.dh1city.focus();");
out.println("document.doct.dh1city.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l24>20){");
out.println("alert(\"hosp1 State must not exceed 20 chars\");");
out.println("document.doct.dh1state.focus();");
out.println("document.doct.dh1state.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l25>20){");
out.println("alert(\"hosp1 Country must not exceed 20 chars\");");
out.println("document.doct.dh1country.focus();");
out.println("document.doct.dh1country.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l26>15){");
out.println("alert(\"hosp1 work phone1 must not exceed 15 chars\");");
out.println("document.doct.dh1w1phone.focus();");
out.println("document.doct.dh1w1phone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l27>15){");
out.println("alert(\"hosp1 work phone2 must not exceed 15 chars\");");
out.println("document.doct.dh1w2phone.focus();");
out.println("document.doct.dh1w2phone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l28>20){");
out.println("alert(\"hosp1 fax must not exceed 20 chars\");");
out.println("document.doct.dh1fax.focus();");
out.println("document.doct.dh1fax.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l29>30){");
out.println("alert(\"hosp1 URL must not exceed 30 chars\");");
out.println("document.doct.dh1url.focus();");
out.println("document.doct.dh1url.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l30>30){");
out.println("alert(\"hosp2 name must not exceed 30 chars\");");
out.println("document.doct.dh2name.focus();");
out.println("document.doct.dh2name.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l31>15){");
out.println("alert(\"hosp2 H.No. must not exceed 15 chars\");");
out.println("document.doct.dh2hno.focus();");
out.println("document.doct.dh2hno.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l32>20){");
out.println("alert(\"hosp2 Street must not exceed 20 chars\");");
out.println("document.doct.dh2str.focus();");
out.println("document.doct.dh2str.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l33>20){");
out.println("alert(\"hosp2 City must not exceed 20 chars\");");
out.println("document.doct.dh2city.focus();");
out.println("document.doct.dh2city.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l34>20){");
out.println("alert(\"hosp2 State must not exceed 20 chars\");");
out.println("document.doct.dh2state.focus();");
out.println("document.doct.dh2state.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l35>20){");
out.println("alert(\"hosp2 Country must not exceed 20 chars\");");
out.println("document.doct.dh2country.focus();");
out.println("document.doct.dh2country.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l36>15){");
out.println("alert(\"hosp2 work phone1 must not exceed 15 chars\");");
out.println("document.doct.dh2dw1phone.focus();");
out.println("document.doct.dh2dw1phone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l37>15){");
out.println("alert(\"hosp2 work phone2 must not exceed 15 chars\");");
out.println("document.doct.h2dw2phone.focus();");
out.println("document.doct.h2dw2phone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l38>20){");
out.println("alert(\"hosp2 fax must not exceed 20 chars\");");
out.println("document.doct.dh2fax.focus();");
out.println("document.doct.dh2fax.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l39>30){");
out.println("alert(\"hosp2 URL must not exceed 30 chars\");");
out.println("document.doct.dh2url.focus();");
out.println("document.doct.dh2url.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l40>30){");
out.println("alert(\"hosp3 name must not exceed 30 chars\");");
out.println("document.doct.dh3name.focus();");
out.println("document.doct.dh3name.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l41>15){");
out.println("alert(\"hosp3 H.No. must not exceed 15 chars\");");
out.println("document.doct.dh3hno.focus();");
out.println("document.doct.dh3hno.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l42>20){");
out.println("alert(\"hosp3 Street must not exceed 20 chars\");");
out.println("document.doct.dh3str.focus();");
out.println("document.doct.dh3str.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l43>20){");
out.println("alert(\"hosp3 City must not exceed 20 chars\");");
out.println("document.doct.dh3city.focus();");
out.println("document.doct.dh3city.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l44>20){");
out.println("alert(\"hosp3 State must not exceed 20 chars\");");
out.println("document.doct.dh3state.focus();");
out.println("document.doct.dh3state.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l45>20){");
out.println("alert(\"hosp3 Country must not exceed 20 chars\");");
out.println("document.doct.dh3country.focus();");
out.println("document.doct.dh3country.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l46>15){");
out.println("alert(\"hosp3 work phone1 must not exceed 15 chars\");");
out.println("document.doct.dh3dw1phone.focus();");
out.println("document.doct.dh3dw1phone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l47>15){");
out.println("alert(\"hosp3 work phone2 must not exceed 15 chars\");");
out.println("document.doct.dh3dw2phone.focus();");
out.println("document.doct.dh3dw2phone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l48>20){");
out.println("alert(\"hosp3 fax must not exceed 20 chars\");");
out.println("document.doct.dh3fax.focus();");
out.println("document.doct.dh3fax.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l49>30){");
out.println("alert(\"hosp3 URL must not exceed 30 chars\");");
out.println("document.doct.dh3url.focus();");
out.println("document.doct.dh3url.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l50>30){");
out.println("alert(\"hosp1 name must not exceed 30 chars\");");
out.println("document.doct.h1dwbname.focus();");
out.println("document.doct.h1dwbname.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l51>20){");
out.println("alert(\"hosp1 city must not exceed 20 chars\");");
out.println("document.doct.h1dwbcity.focus();");
out.println("document.doct.h1dwbcity.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l52>20){");
out.println("alert(\"hosp1 state must not exceed 20 chars\");");
out.println("document.doct.h1dwbstate.focus();");
out.println("document.doct.h1dwbstate.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l53>20){");
out.println("alert(\"hosp1 country must not exceed 20 chars\");");
out.println("document.doct.h1dwbcountry.focus();");
out.println("document.doct.h1dwbcountry.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l54>15){");
out.println("alert(\"hosp1 phone must not exceed 15 chars\");");
out.println("document.doct.h1dwbphone.focus();");
out.println("document.doct.h1dwbphone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l55>30){");
out.println("alert(\"hosp2 name must not exceed 20 chars\");");
out.println("document.doct.h2dwbname.focus();");
out.println("document.doct.h2dwbname.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l56>20){");
out.println("alert(\"hosp2 city must not exceed 20 chars\");");
out.println("document.doct.h2dwbcity.focus();");
out.println("document.doct.h2dwbcity.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l57>20){");
out.println("alert(\"hosp2 state must not exceed 20 chars\");");
out.println("document.doct.h2dwbstate.focus();");
out.println("document.doct.h2dwbstate.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l58>20){");
out.println("alert(\"hosp2 country must not exceed 20 chars\");");
out.println("document.doct.h2dwbcountry.focus();");
out.println("document.doct.h2dwbcountry.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(l59>15){");
out.println("alert(\"hosp2 phone must not exceed 20 chars\");");
out.println("document.doct.h2dwbphone.focus();");
out.println("document.doct.h2dwbphone.select();");
out.println("return false;");
out.println("}");
out.println("else");
out.println("if(!isNaN(str2.charAt(0) ) ){");
out.println("alert(\"Enter only character value in first digit of doctor name field\");");
out.println("document.doct.dname.focus();");
out.println("document.doct.dname.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str10.charAt(0) ) ){");
out.println("alert(\"Enter only character value in first digit of City field\");");
out.println("document.doct.dcity.focus();");
out.println("document.doct.dcity.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str11.charAt(0) ) ){");
out.println("alert(\"Enter only character value in first digit of state field\");");
out.println("document.doct.dstate.focus();");
out.println("document.doct.dstate.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str12.charAt(0) ) ){");
out.println("alert(\"Enter only character value in first digit of country field\");");
out.println("document.doct.dcountry.focus();");
out.println("document.doct.dcountry.select();");
out.println("return false;");
 out.println("}");
out.println("else");
out.println("if(!isNaN(str2)){");
out.println("alert(\"Enter only character values in doctor name field\");");
out.println("document.doct.dname.focus();");
out.println("document.doct.dname.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str4)){");
out.println("alert(\"Enter only character values in doctor qualification field\");");
out.println("document.doct.dqual.focus();");
out.println("document.doct.dqual.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str5)){");
out.println("alert(\"Enter only character values in doctor specialization field\");");
out.println("document.doct.dspec.focus();");
out.println("document.doct.dspec.select();");
out.println("return false;");
 out.println("}");
out.println("else");
out.println("if(!isNaN(str7)){");
out.println("alert(\"Enter only character values in achievement field\");");
out.println("document.doct.dachieve.focus();");
out.println("document.doct.dachieve.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str9)){");
out.println("alert(\"Enter only character values in street field\");");
out.println("document.doct.dstr.focus();");
out.println("document.doct.dstr.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str10)){");
out.println("alert(\"Enter only character values in city field\");");
out.println("document.doct.dcity.focus();");
out.println("document.doct.dcity.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str11)){");
out.println("alert(\"Enter only character values in state field\");");
out.println("document.doct.state.focus();");
out.println("document.doct.state.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str12)){");
out.println("alert(\"Enter only character values in country field\");");
out.println("document.doct.dcountry.focus();");
out.println("document.doct.dcountry.select();");
out.println("return false;");
 out.println("}");
 out.println("else");
out.println("if(!isNaN(str18)){");
out.println("alert(\"Enter only character values in Email field\");");
out.println("document.doct.demail.focus();");
out.println("document.doct.demail.select();");
out.println("return false;");
 out.println("}");
out.println("else");
out.println("if(l20>0)");
out.println("{");
out.println("if(!isNaN(str20)){");
out.println("alert(\"Enter only character values in hosp1 name field\");");
out.println("document.doct.dh1name.focus();");
out.println("document.doct.dh1name.select();");
out.println("return false;");
 out.println("}");
 out.println("}");
 out.println("else");
 out.println("if(l22>0)");
out.println("{");
out.println("if(!isNaN(str22)){");
out.println("alert(\"Enter only character values in hosp1 street field\");");
out.println("document.doct.dh1str.focus();");
out.println("document.doct.dh1str.select();");
out.println("return false;");
out.println("}}");
out.println("else");
out.println("if(l23>0)");
out.println("{");
out.println("if(!isNaN(str23)){");
out.println("alert(\"Enter only character values in hosp1 city field\");");
out.println("document.doct.dh1city.focus();");
out.println("document.doct.dh1city.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l24>0)");
out.println("{");
out.println("if(!isNaN(str24)){");
out.println("alert(\"Enter only character values in hosp1 state field\");");
out.println("document.doct.dh1state.focus();");
out.println("document.doct.dh1state.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l25>0)");
out.println("{");
out.println("if(!isNaN(str25)){");
out.println("alert(\"Enter only character values in hosp1 country field\");");
out.println("document.doct.dh1country.focus();");
out.println("document.doct.dh1country.select();");
out.println("return false;");
out.println("}}");
out.println("else");
out.println("if(l29>0)");
out.println("{");
out.println("if(!isNaN(str29)){");
out.println("alert(\"Enter only character values in hosp1 URL field\");");
out.println("document.doct.dh1url.focus();");
out.println("document.doct.dh1url.select();");
out.println("return false;");
out.println("}}");
out.println("else");
out.println("if(l30>0)");
out.println("{");
out.println("if(!isNaN(str30)){");
out.println("alert(\"Enter only character values in hosp2 name field\");");
out.println("document.doct.dh2name.focus();");
out.println("document.doct.dh2name.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l32>0)");
out.println("{");
out.println("if(!isNaN(str32)){");
out.println("alert(\"Enter only character values in hosp2 street field\");");
out.println("document.doct.dh2str.focus();");
out.println("document.doct.dh2str.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l33>0)");
out.println("{");
out.println("if(!isNaN(str33)){");
out.println("alert(\"Enter only character values in hosp2 city field\");");
out.println("document.doct.dh2city.focus();");
out.println("document.doct.dh2city.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l34>0)");
out.println("{");
out.println("if(!isNaN(str34)){");
out.println("alert(\"Enter only character values in hosp2 state field\");");
out.println("document.doct.dh2state.focus();");
out.println("document.doct.dh2state.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l35>0)");
out.println("{");
out.println("if(!isNaN(str35)){");
out.println("alert(\"Enter only character values in hosp2 country field\");");
out.println("document.doct.dh2country.focus();");
out.println("document.doct.dh2country.select();");
out.println("return false;");
 out.println("}}");
  out.println("else");
  out.println("if(l39>0)");
out.println("{");
out.println("if(!isNaN(str39)){");
out.println("alert(\"Enter only character values in hosp2 URL field\");");
out.println("document.doct.dh2url.focus();");
out.println("document.doct.dh2url.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l40>0)");
out.println("{");
out.println("if(!isNaN(str40)){");
out.println("alert(\"Enter only character values in hosp3 name field\");");
out.println("document.doct.dh3name.focus();");
out.println("document.doct.dh3name.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l42>0)");
out.println("{");
out.println("if(!isNaN(str42)){");
out.println("alert(\"Enter only character values in hosp3 street field\");");
out.println("document.doct.dh3str.focus();");
out.println("document.doct.dh3str.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l43>0)");
out.println("{");
out.println("if(!isNaN(str43)){");
out.println("alert(\"Enter only character values in hosp3 city field\");");
out.println("document.doct.dh3city.focus();");
out.println("document.doct.dh3city.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l44>0)");
out.println("{");
out.println("if(!isNaN(str44)){");
out.println("alert(\"Enter only character values in hosp3 state field\");");
out.println("document.doct.dh3state.focus();");
out.println("document.doct.dh3state.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l45>0)");
out.println("{");
out.println("if(!isNaN(str45)){");
out.println("alert(\"Enter only character values in hosp3 country field\");");
out.println("document.doct.dh3country.focus();");
out.println("document.doct.dh3country.select();");
out.println("return false;");
 out.println("}}");
  out.println("else");
  out.println("if(l49>0)");
out.println("{");
out.println("if(!isNaN(str49)){");
out.println("alert(\"Enter only character values in hosp3 URL field\");");
out.println("document.doct.dh3url.focus();");
out.println("document.doct.dh3url.select();");
out.println("return false;");
 out.println("}}");
out.println("else");
out.println("if(l50>0)");
out.println("{");
out.println("if(!isNaN(str50)){");
out.println("alert(\"Enter only character values in hosp1 name field\");");
out.println("document.doct.h1dwbname.focus();");
out.println("document.doct.h1dwbname.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l51>0)");
out.println("{");
out.println("if(!isNaN(str51)){");
out.println("alert(\"Enter only character values in hosp1 city field\");");
out.println("document.doct.h1dwbcity.focus();");
out.println("document.doct.h1dwbcity.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l52>0)");
out.println("{");
out.println("if(!isNaN(str52)){");
out.println("alert(\"Enter only character values in hosp1 state field\");");
out.println("document.doct.h1dwbstate.focus();");
out.println("document.doct.h1dwbstate.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l53>0)");
out.println("{");
out.println("if(!isNaN(str53)){");
out.println("alert(\"Enter only character values in hosp1 country field\");");
out.println("document.doct.h1dwbcountry.focus();");
out.println("document.doct.h1dwbcountry.select();");
out.println("return false;");
 out.println("}}");
out.println("else");
out.println("if(l55>0)");
out.println("{");
out.println("if(!isNaN(str55)){");
out.println("alert(\"Enter only character values in hosp2 name field\");");
out.println("document.doct.h2dwbname.focus();");
out.println("document.doct.h2dwbname.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l56>0)");
out.println("{");
out.println("if(!isNaN(str56)){");
out.println("alert(\"Enter only character values in hosp2 city field\");");
out.println("document.doct.h2dwbcity.focus();");
out.println("document.doct.h2dwbcity.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l57>0)");
out.println("{");
out.println("if(!isNaN(str57)){");
out.println("alert(\"Enter only character values in hosp2 state field\");");
out.println("document.doct.h2dwbstate.focus();");
out.println("document.doct.h2dwbstate.select();");
out.println("return false;");
 out.println("}}");
 out.println("else");
 out.println("if(l58>0)");
out.println("{");
out.println("if(!isNaN(str58)){");
out.println("alert(\"Enter only character values in hosp2 country field\");");
out.println("document.doct.h2dwbcountry.focus();");
out.println("document.doct.h2dwbcountry.select();");
out.println("return false;");
 out.println("}}");
 out.println("}");
out.println("</script>");
out.println("</HEAD>");
out.println("<BODY background='c:/javawebserver2.0/servlets/wedflo_15.gif'>");
out.println("<CENTER>");		
out.println("<form  name=\"doct\" method=post action=\"doctins\"> ");
out.println("<input type=hidden name=username value="+uid+">");
out.println("<font size=7 face=\"arial black\" color=\"red\">+</font>&nbsp;&nbsp;&nbsp;<b><font size=6 color=\"green\"><u>Doctor's Registration Form</u></font></b>&nbsp;&nbsp;&nbsp;<font size=7 face=\"arial black\" color=\"red\">+</font>");
out.println("<TABLE >");
out.println("<tr>");
out.println("<td><input type=hidden name=dcode value="+s+" size=20> </td>");
out.println("</tr>");
out.println("<TR><TD><B>Doctor Name :</B></TD>");
out.println("    <td><INPUT TYPE=\"text\" NAME=\"dname\" size =20></td>");
out.println("</tr>");
out.println("<tr>");
out.println("    <TD><B>Age:</B></TD>");
out.println("    <TD><INPUT TYPE=\"text\" NAME=\"dage\" size=20></TD>");
out.println("</TR>");
out.println("<TR>");
out.println("   	<TD><B>Qualification(s)</TD>");
out.println("</tr>");
out.println("<tr>");
out.println("	<td><b>(use , as seperator):</b></td>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dqual\" size=20></TD>");
out.println("</tr>");
out.println("<tr>");
out.println("     	<TD><B>Specialization: </TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dspec\" size=20></TD></B>");
out.println("</TR>");
out.println("<tr>");
out.println("	<td><b>Experience:</b></td>");
out.println("	<td><select name=\"dexp\">");
out.println("	<option value=01>01");
out.println("		<option value=02>02");
out.println("		<option value=03>03");
out.println("		<option value=04>04");
out.println("		<option value=05>05");
out.println("		<option value=06>06");
out.println("		<option value=07>07");
out.println("		<option value=08>08");
out.println("		<option value=09>09");
out.println("		<option value=10>10");
out.println("		<option value=11>11");
out.println("		<option value=12>12");
out.println("		<option value=13>13");
out.println("		<option value=14>14");
out.println("		<option value=15>15");
out.println("		<option value=16>16");
out.println("		<option value=17>17");
out.println("		<option value=18>18");
out.println("		<option value=19>19");
out.println("		<option value=20>20");
out.println("	</select>");
out.println("       </td>");
out.println("</tr>");
out.println("<tr>");
out.println("<td><b>Achievements</b></td>");
out.println("<td><textarea name=\"dachieve\" rows=3 cols=14></textarea></td>");
out.println("</tr>");
out.println("<TR>");
out.println("        <TD><B>House No.:</TD>");
out.println("   	<TD><input type=\"text\" name=dhno size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Street:</td>");
out.println("	<td><input type=\"text\" name=dstr size=20></td>");
out.println("</tr>");
out.println("<TR>");
out.println("   	<TD><B>City:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dcity\" size=20></TD>");
out.println("        <TD><B>State</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dstate\" size=20></TD>");
out.println("</TR>");
out.println("<tr>");
out.println("	<td><b>Country:</td>");
out.println("	<td><input type=\"text\" name=\"dcountry\" size=20></td>");
out.println("	<TD><b>Zip Code:</td>");
out.println("	<td><input type=\"text\" name=\"dzcode\" size=20></td>");
out.println("</tr>");
out.println("<TR>");
out.println("   	<TD><B>Phone(Workplace):</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dwphone\" size=20></TD>");
out.println("	<td><b>Phone(Residence):</td>");
out.println("	<td><input type=\"text\" name=\"drphone\" size=20></td>");
out.println("</TR>");
out.println("<TR>");
out.println("   	<TD><B>Mobile</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dmobile\" size=20></TD>");
out.println("   	<TD><B>Fax</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dfax\" size=20></TD>");
out.println("</tr>");
out.println("<tr>");
out.println("   	<TD><B>E-mail Id</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"demail\" size=20></TD>");
out.println("</TR>");
out.println("<tr>");
out.println("        <td><b>Available Timings:</b></td>");
out.println("	<td><input type=\"text\" name=\"datime\" size=20></td>");
out.println("</tr>");
out.println("<TR>");
out.println("   	<TD><B>Hospital(s)/Clinic(s) Working for:</TD>");
out.println("</TR><BR>");
out.println("<TR>");
out.println("	 <TD><B>1.Hospital Name :</B></TD>");
out.println("	 <td><INPUT TYPE=\"text\" NAME=\"dh1name\" size =20></td>");
out.println("</tr>");
out.println("<TR>");
out.println("        <TD><B>House No.:</TD>");
out.println("   	<TD><input type=\"text\" name=dh1hno size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Street:</td>");
out.println("	<td><input type=\"text\" name=dh1str size=20></td>");
out.println("</tr>");

out.println("<TR>");
out.println("   	<TD><B>City:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh1city\" size=20></TD>");
out.println("	 <TD><B>State</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh1state\" size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Country:</td>");
out.println("	<td><input type=\"text\" name=\"dh1country\" size=20></td>");
out.println("</tr>");


out.println("<TR>");
out.println("   	<TD><B>Phone1:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh1w1phone\" size=20></TD>");
out.println("	<td><b>Phone2:</td>");
out.println("	<td><input type=\"text\" name=\"dh1w2phone\" size=20></td>");
out.println("</tr>");

out.println("<tr>");
out.println("        <td><B>Fax :</td>");
out.println("	<td><INPUT TYPE=\"text\" NAME=\"dh1fax\" size=20></td>");
out.println("	<td><B>URL :</td>");
out.println("        <td><INPUT TYPE=\"text\" NAME=\"dh1url\" size=20></TD>");
out.println("</TR>");
out.println("<TR>");
out.println("	 <TD><B>2.Hospital Name :</B></TD>");
out.println("	 <td><INPUT TYPE=\"text\" NAME=\"dh2name\" size =20></td>");
out.println("</tr>");
out.println("<TR>");
out.println("        <TD><B>House No.:</TD>");
out.println("   	<TD><input type=\"text\" name=dh2hno size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Street:</td>");
out.println("	<td><input type=\"text\" name=dh2str size=20></td>");
out.println("</tr>");

out.println("<TR>");
out.println("   	<TD><B>City:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh2city\" size=20></TD>");
out.println("	 <TD><B>State</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh2state\" size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Country:</td>");
out.println("	<td><input type=\"text\" name=\"dh2country\" size=20></td>");
out.println("</tr>");


out.println("<TR>");
out.println("   	<TD><B>Phone1:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh2dw1phone\" size=20></TD>");
out.println("	<td><b>Phone2:</td>");
out.println("	<td><input type=\"text\" name=\"h2dw2phone\" size=20></td>");
out.println("</tr>");

out.println("<tr>");
out.println("        <td><B>Fax :</td>");
out.println("	<td><INPUT TYPE=\"text\" NAME=\"dh2fax\" size=20></td>");
out.println("	<td><B>URL :</td>");
out.println("        <td><INPUT TYPE=\"text\" NAME=\"dh2url\" size=20></TD>");
out.println("</TR>");

out.println("<TR>");
out.println("	 <TD><B>3.Hospital Name :</B></TD>");
out.println("	 <td><INPUT TYPE=\"text\" NAME=\"dh3name\" size =20></td>");
out.println("</tr>");
out.println("<TR>");
out.println("        <TD><B>House No.:</TD>");
out.println("   	<TD><input type=\"text\" name=dh3hno size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Street:</td>");
out.println("	<td><input type=\"text\" name=dh3str size=20></td>");
out.println("</tr>");

out.println("<TR>");
out.println("   	<TD><B>City:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh3city\" size=20></TD>");
out.println("	 <TD><B>State</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh3state\" size=20></TD>");
out.println("</TR>");

out.println("<tr>");
out.println("	<td><b>Country:</td>");
out.println("	<td><input type=\"text\" name=\"dh3country\" size=20></td>");
out.println("</tr>");


out.println("<TR>");
out.println("   	<TD><B>Phone1:</TD>");
out.println("   	<TD><INPUT TYPE=\"text\" NAME=\"dh3dw1phone\" size=20></TD>");
out.println("	<td><b>Phone2:</td>");
out.println("	<td><input type=\"text\" name=\"dh3dw2phone\" size=20></td>");
out.println("</tr>");

out.println("<tr>");
out.println("        <td><B>Fax :</td>");
out.println("	<td><INPUT TYPE=\"text\" NAME=\"dh3fax\" size=20></td>");
out.println("	<td><B>URL :</td>");
out.println("        <td><INPUT TYPE=\"text\" NAME=\"dh3url\" size=20></TD>");
out.println("</TR>");
out.println("<TR>");
out.println("   	<TD><B>Hospital/Clinic Worked Before:</TD>");
out.println("</TR><BR>");
out.println("<TR>");
out.println("	     <TD><B>1.Hospital Name :</B></TD>");
out.println("	     <td><INPUT TYPE=\"text\" NAME=\"h1dwbname\" size =20></td>");
out.println("</tr>");
out.println("<tr>");
out.println("            <td><B>City:</b></td>");
out.println("	<td><input type=\"text\" name=\"h1dwbcity\" size=20></td>");
out.println("	<td><B>State:</b></td>");
out.println("	<td><input type=\"text\" name=\"h1dwbstate\" size=20></td>");
out.println("</tr>");

out.println("<tr>");
out.println("	<td><b>Country:</td>");
out.println("	<td><input type=\"text\" name=\"h1dwbcountry\" size=20></td>");
out.println("            <td><B>Phone:</td>");
out.println("            <td><INPUT TYPE=\"text\" NAME=\"h1dwbphone\" size=20></td>");
out.println("</tr>");

out.println("<TR>");
out.println("	     <TD><B>2.Hospital Name :</B></TD>");
out.println("	     <td><INPUT TYPE=\"text\" NAME=\"h2dwbname\" size =20></td>");
out.println("</tr>");
out.println("<tr>");
out.println("            <td><B>City:</b></td>");
out.println("	<td><input type=\"text\" name=\"h2dwbcity\" size=20></td>");
out.println("	<td><B>State:</b></td>");
out.println("	<td><input type=\"text\" name=\"h2dwbstate\" size=20></td>");
out.println("</tr>");

out.println("<tr>");
out.println("	<td><b>Country:</td>");
out.println("	<td><input type=\"text\" name=\"h2dwbcountry\" size=20></td>");
out.println("            <td><B>Phone:</td>");
out.println("            <td><INPUT TYPE=\"text\" NAME=\"h2dwbphone\" size=20></td>");
out.println("</tr>");
out.println("</table></center>");
out.println("<br><br><br>");
out.println("<center>");
out.println("	<td><input type=\"submit\" value=\"Submit\" onClick=\" return doccheck()\"></td>");
out.println("<td><input type=\"button\" value=\"Back\" onClick=window.history.go(-1)></td>");
out.println("</center>");
out.println("</form>");
out.println("</BODY>");
out.println("</HTML>");
}
}
catch(Exception e)
{
e.printStackTrace();
}
}
}
