<table border="0" width="100%" cellpadding="5">
  <tr>
    <td width="100%">
      <table border="0" width="100%" bgcolor="#990033" cellpadding="3" cellspacing="1">
        <tr>
          <td width="100%" bgcolor="#990033">
            <font face="Arial,helvetica,verdana,geneva" size="2" color="#FFFFFF"><b>Computer
            Studies</b></font> 
          </td> 
        </tr> 
        <tr> 
          <td width="100%" bgcolor="#FFE6EE"> 
            <table border="0" width="100%" cellspacing="0" cellpadding="0"> 
              <tr> 
                <td width="100%" bgcolor="#FFFFFF"> 
                  <table border="0" width="100%" cellspacing="1" cellpadding="2"> 
                    <tr> 
                      <td width="90%" valign="top"><font face="Arial,helvetica,verdana,geneva" size="2"><%=ForumQuestion%></font></td> 
                    </tr> 
                    <tr> 
                      <td width="90%" valign="top"> 
                        <p align="right"><font face="Arial,helvetica,verdana,geneva" size="1"><img border="0" src="../images/pictomessage.gif" align="texttop" alt="Messages"> 
                        <%=NumofMsg%>&nbsp;&nbsp;</font></td> 
                    </tr> 
                  </table> 
                </td> 
              </tr> 
            </table> 
          </td> 
        </tr> 
      </table> 
    </td> 
  </tr> 
</table>