import java.io.*;
import java.sql.*;
import javax.servlet.*;
import javax.servlet.http.*;
public class credit extends HttpServlet
{
    String ino,rno,amt;
    public void doGet(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException
    {
       PrintWriter out=res.getWriter();
       res.setContentType("text/html");
       ino=req.getParameter("ino");
       rno=req.getParameter("rno");
       amt=req.getParameter("amt");
       out.println("<html><body>");
       out.println("<script>");

       out.println("function typ()");
       out.println("{");
       out.println("var a=document.forms[0].type.value;");   
       out.println("if(a.length == 0)");
       out.println("{");
       out.println("alert(\"Null field\");");
       out.println("document.forms[0].type.focus();");
       out.println("return;");
       out.println("}");
       out.println("else");
       out.println("{");
       out.println("for(i=0;i<a.length;i++)");
       out.println("{");
       out.println("var b=a.substring(i,i+1);");
       out.println("if(!(b >='a' && b <= 'z' || b>='A' && b<='Z'))");
       out.println("{");
       out.println("alert(\"Enter alphabets only\");");
       out.println("document.forms[0].type.focus();");
       out.println("document.forms[0].type.value=\"\";");
       out.println("return;");
       out.println("}");
       out.println("}");
       out.println("}");
       out.println("document.forms[0].type.value=a;");
       out.println("}");

       out.println("function check()");
       out.println("{");
       out.println("var a=document.forms[0].no.value;");
       out.println("var s1=0;");
       out.println("var s=0;");
       out.println("for(var i=0;i<a.length;i++)");
       out.println("{");
       out.println("var c=a.charAt(i);");
       out.println("if(c%2==0)");
       out.println("{");
       out.println("var e=c;");
       out.println("s1=parseInt(s1)+parseInt(e);");
       out.println("}");
       out.println("else");
       out.println("{");
       out.println("var o=c;");
       out.println("s=parseInt(s)+parseInt(o);");
       out.println("}");
       out.println("}");
       out.println("if(s1%10!=0 || s%10!=0)");
       out.println("{");
       out.println("alert(\"Invalid Credit Card Number\");");
       out.println("document.forms[0].no.focus();");
       out.println("document.forms[0].no.value=\"\";");
       out.println("return;");
       out.println("}");

       out.println("else if(a.length == 0)");
       out.println("{");
       out.println("alert(\"Null field\");");
       out.println("document.forms[0].no.focus();");
       out.println("return;");
       out.println("}");
       out.println("else");
       out.println("{");
       out.println("for(i=0;i<a.length;i++)");
       out.println("{");
       out.println("var b=a.substring(i,i+1);");
       out.println("if(!(b >=1 || b <= 9))");
       out.println("{");
       out.println("alert(\"Enter valid numbers only\");");
       out.println("document.forms[0].no.focus();");
       out.println("document.forms[0].no.value=\"\";");
       out.println("return;");
       out.println("}");
       out.println("}");
       out.println("}");
       out.println("document.forms[0].no.value=a;");
       out.println("}");

       out.println("function mon()");
       out.println("{");
       out.println("var dt=document.forms[0].edt.value;");
       out.println("if(dt.length == 0)");
       out.println("{");
       out.println("alert(\"Null field\");");
       out.println("document.forms[0].edt.focus();");
       out.println("return;");
       out.println("}");
       out.println("var p=dt.length;");
       out.println("var x=dt.indexOf(\"-\");");
       out.println("var d=dt.substring(0,x);");
       out.println("var y=dt.lastIndexOf(\"-\");");
       out.println("var m=dt.substring(x+1,y);");
       out.println("var z=dt.substring(y+1,p);");
       out.println("if(m==01 || m==1 || m==\"jan\" || m==\"january\") var f=\"jan\";");
       out.println("else if(m==02 || m==2 || m==\"feb\" || m==\"february\") var f=\"feb\";");
       out.println("else if(m==03 || m==3 || m==\"mar\" || m==\"march\") var f=\"mar\";");
       out.println("else if(m==04 || m==4 || m==\"apr\" || m==\"april\") var f=\"apr\";");
       out.println("else if(m==05 || m==5 || m==\"may\" || m==\"may\") var f=\"may\";");
       out.println("else if(m==06 || m==6 || m==\"jun\" || m==\"june\") var f=\"jun\";");
       out.println("else if(m==07 || m==7 || m==\"jul\" || m==\"july\") var f=\"jul\";");
       out.println("else if(m==08 || m==8 || m==\"aug\" || m==\"august\") var f=\"aug\";");
       out.println("else if(m==09 || m==9 || m==\"sep\" || m==\"september\") var f=\"sep\";");
       out.println("else if(m==10 || m==10 || m==\"oct\" || m==\"october\") var f=\"oct\";");
       out.println("else if(m==11 || m==11 || m==\"nov\" || m==\"november\") var f=\"nov\";");
       out.println("else if(m==12 || m==12 || m==\"dec\" || m==\"december\") var f=\"dec\";");
       out.println("var dd=d+\"-\"+f+\"-\"+z;");
       out.println("document.forms[0].edt.value=dd;");
       out.println("}");

       out.println("function nam()");
       out.println("{");
       out.println("var a=document.forms[0].name.value;");   
       out.println("if(a.length == 0)");
       out.println("{");
       out.println("alert(\"Null field\");");
       out.println("document.forms[0].name.focus();");
       out.println("return;");
       out.println("}");
       out.println("else");
       out.println("{");
       out.println("for(i=0;i<a.length;i++)");
       out.println("{");
       out.println("var b=a.substring(i,i+1);");
       out.println("if(!(b >='a' && b <= 'z' || b>='A' && b<='Z'))");
       out.println("{");
       out.println("alert(\"Enter alphabets only\");");
       out.println("document.forms[0].name.focus();");
       out.println("document.forms[0].name.value=\"\";");
       out.println("return;");
       out.println("}");
       out.println("}");
       out.println("}");
       out.println("document.forms[0].name.value=a;");
       out.println("}");

       out.println("function bnk()");
       out.println("{");
       out.println("var a=document.forms[0].bank.value;");   
       out.println("if(a.length == 0)");
       out.println("{");
       out.println("alert(\"Null field\");");
       out.println("document.forms[0].bank.focus();");
       out.println("return;");
       out.println("}");
       out.println("else");
       out.println("{");
       out.println("for(i=0;i<a.length;i++)");
       out.println("{");
       out.println("var b=a.substring(i,i+1);");
       out.println("if(!(b >='a' && b <= 'z' || b>='A' && b<='Z'))");
       out.println("{");
       out.println("alert(\"Enter alphabets only\");");
       out.println("document.forms[0].bank.focus();");
       out.println("document.forms[0].bank.value=\"\";");
       out.println("return;");
       out.println("}");
       out.println("}");
       out.println("}");
       out.println("document.forms[0].bank.value=a;");
       out.println("}");

       out.println("</script>");
       out.println("<center><table>");
       out.println("<form method=post action=http://localhost:8080/servlet/credit1>");
       out.println("<input type=hidden name=rno value="+rno+">");
       out.println("<input type=hidden name=ino value="+ino+">");
       out.println("<input type=hidden name=amt value="+amt+">");
       out.println("<caption><font size=5><b><u>Credit Card Details</u></b></font></caption>");
       out.println("<tr><td><label>Card Type:</label></td><td><input size=20 name=type onblur=typ()></td>");
       out.println("<td><label>Card No:</label></td><td><input size=20 name=no ></td></tr>");
       out.println("<tr><td><label>Card Holder Name:</label></td><td><input size=20 name=name onfocus=\"check();\"></td>");
       out.println("<td><label>Expiry Date:</label></td><td><input size=20 name=edt onfocus=\"nam();\"></td></tr>");
       out.println("<tr><td><label>Bank Name:</label></td><td><input size=20 name=bank onfocus=\"mon();\"></td></tr>");
       out.println("<table><tr><td align=center><input type=submit value=\" Insert \" onfocus=bnk()></td></tr></table>");
    }
}
